services:
  frontend:
    build: ./client
    restart: unless-stopped

  backend:
    build: ./server
    restart: unless-stopped

  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend